---
title: "Course Project 1"
author: "Gustavo Sánchez"
date: "3/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

* This is the Homework (Course Project 1) by Data_analisys course.

* The PNG files was create by separate R code file (`plot1.R`, `plot2.R`, etc.) 

The four plots constructed are shown below. 


## Plot 1

## R code
```{r echo=FALSE}
Data <- read.csv('C:/Users/GUSTAVO/Desktop/Data analisys/Taller 1/data1.csv', header=TRUE , se= ";", colClasses = c("character" ,"character" ,"numeric","numeric","numeric","numeric","numeric","numeric","numeric"))


head(Data)
str(Data)
date <- paste(Data[,1],Data[,2],sep=" "); head(date)
d<- cbind(date,Data[,-c(1,2)]); head(d)

d$date <- as.POSIXct(strptime(d$date, 
                                    format="%d/%m/%Y %H:%M:%S"))
library(datasets)

p<- hist(d$Global_active_power, col="green", xlab=expression("Global_active_power"))

png(file = "Plot1", height = 480, width = 480, )  # Una figura de 5x10 cm

p    

dev.off()  
```

`
## Plot2


```{r}
Data <- read.csv('C:/Users/GUSTAVO/Desktop/Data analisys/Taller 1/data1.csv', header=TRUE , se= ";", colClasses = c("character" ,"character" ,"numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
date <- paste(Data[,1],Data[,2],sep=" "); head(date)
d<- cbind(date,Data[,-c(1,2)]); head(d)

d$date <- as.POSIXct(strptime(d$date, 
                              format="%d/%m/%Y %H:%M:%S"))


library(datasets)

p<-plot(d[,1],d[,2],type="l",ylab=expression("Global active power (Kilowatts)"),xlab=" ", main="Global active power")
png(file = "Plot2", height = 480, width = 480, )  # Una figura 

p    

dev.off() 
```

## Plot3

```{r}
Data <- read.csv('C:/Users/GUSTAVO/Desktop/Data analisys/Taller 1/data1.csv', header=TRUE , se= ";", colClasses = c("character" ,"character" ,"numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
date <- paste(Data[,1],Data[,2],sep=" "); head(date)
d<- cbind(date,Data[,-c(1,2)]); head(d)

d$date <- as.POSIXct(strptime(d$date, 
                              format="%d/%m/%Y %H:%M:%S"))


library(datasets)
y1<- d[,6]
y2<- d[,7]
y3<- d[,8]


plot(d[,1],y1, type = "l" ,ylab="Energy Sub metering",xlab=" ", main="")
lines(d[,1],y2,type="l",col="red")
lines(d[,1],y3,type="l",col="blue", ylab="Energy Sub metering", xlab=" ", main="")
legend("topright",       c("Sub_metering_1","Sub metering_2","Sub metering_3"), col= c("black","red","blue")  , lty=1, cex=0.8)

par(new=TRUE)
plot(d[,1],d[,7], col = "red",ylab="",xlab=" ", main="")
par(new=TRUE)
plot(d[,1],d[,8], type = "l", col = "blue",ylab=expression("Energy Sub metering"),xlab=" ", main="")


```


## Plot4

```{r}
Data <- read.csv('C:/Users/GUSTAVO/Desktop/Data analisys/Taller 1/data1.csv', header=TRUE , se= ";", colClasses = c("character" ,"character" ,"numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
date <- paste(Data[,1],Data[,2],sep=" "); head(date)
d<- cbind(date,Data[,-c(1,2)]); head(d)

d$date <- as.POSIXct(strptime(d$date, 
                              format="%d/%m/%Y %H:%M:%S"))


library(datasets)
y1<- d[,6]
y2<- d[,7]
y3<- d[,8]
y4<- d[,4]
y5<- d[,3]
par(mfrow=c(2,2), mar=c(5,4,2,1))

#Plot1
plot(d[,1],d[,2],type="l",ylab=expression("Global active power (Kilowatts)"),xlab=" ", main="Global active power")
#plot2
plot(d[,1],y4, type = "l" ,ylab="Voltage",xlab="date/time ", main="")
#Plot3

plot(d[,1],y1, type = "l" ,ylab="Energy Sub metering",xlab=" ", main="")
lines(d[,1],y2,type="l",col="red")
lines(d[,1],y3,type="l",col="blue", ylab="Energy Sub metering", xlab=" ", main="")
legend("topright",       c("Sub_metering_1","Sub metering_2","Sub metering_3"), col= c("black","red","blue")  , lty=1, cex=0.1)



#plot#4
plot(d[,1],y5, type = "l" ,ylab="Global_reactive_power",xlab="date/time ", main="")

```



